[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'
rev = 'v3.4.2'

[[plugins]]
repo = 'Shougo/pum.vim'
rev = '1.0'

[[plugins]]
repo = 'Shougo/ddc-around'
rev = 'c30a1844509c424f2e59550db856dfb1bc0f24eb'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'
rev = 'd8bd794b9868cf3ee646c6dc9161bcdbe974a9c6'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'
rev = '56d061d3379565e0a3f3b987fc13e3887a97e91c'

[[plugins]]
repo = 'matsui54/ddc-source-buffer'
rev = 'e417e47964788b0211c80252757531f7a3881178'

[[plugins]]
repo = 'Shougo/ddc.vim'
rev = 'v2.5.1'
hook_add = '''
    source $HOME/.vim/conf/ddc.vim
'''

[[plugins]]
repo = 'preservim/nerdtree'
hook_add = '''
    map <C-n> :NERDTreeToggle<CR>
'''

[[plugins]]
repo = 'preservim/vim-markdown'
hook_add = '''
    source $HOME/.vim/conf/vim-markdown.vim
'''

[[plugins]]
repo = 'kannokanno/previm'

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
    source $HOME/.vim/conf/vim-easymotion.vim
'''

[[plugins]]
repo = 'octol/vim-cpp-enhanced-highlight'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
    let g:indentLine_color_term =239
    let g:indentLine_color_gui = '#708090'
    let g:indentLine_char = '¦'
    set list listchars=tab:\¦\
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    source $HOME/.vim/conf/vim-airline.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'altercation/vim-colors-solarized'
hook_add = '''
    source $HOME/.vim/conf/vim-colors-solarized.vim
'''

[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = ['vim-lsp']

[[plugins]]
repo = 'shun/ddc-vim-lsp'

[[plugins]]
repo = 'Shougo/ddc-source-vim-lsp'
rev = 'c050eeeca84834ab02929f3df521da9add9eb587'
